[package]
name = "godothub"
version = "1.4.3"
description = "Godot Version and Project Management"
authors = ["Ryko"]
edition = "2021"

[lib]
name = "godothub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.1"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
url = "2"
tokio = { version = "1.52.3", features = ["full"] }
futures-util = "0.3.32"
zip = "8.6.0"
uuid = { version = "1.23.4", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
base64 = "0.22.1"
tauri-plugin-prevent-default = "5"
feed-rs = "2"
quick-xml = "0.41"
tauri-plugin-single-instance = "2.0.0"
notify = "6"
tauri-plugin-updater = "2.10.1"
tauri-plugin-window-state = "2"
tauri-plugin-notification = "2"
trash = "3"
thiserror = "2"
tauri-plugin-discord-rpc = { git = "https://github.com/Youwes09/tauri-plugin-discord-rpc" }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading"] }
