import { invoke } from '@tauri-apps/api/core'
import { projectsApi, getCachedProjectIcon, getCachedProjectName } from '../api/projects'
import { versionsApi } from '../api/versions'
import { gitApi } from '../api/git'
import { gitAuthApi } from '../api/gitAuth'
import { settingsApi } from '../api/settings'
import { templatesApi } from '../api/templates'
import { categoriesApi } from '../api/categories'
import { workspacesApi } from '../api/workspaces'
import { changelogApi } from '../api/changelog'
import { updatesApi } from '../api/updates'
import { newsApi } from '../api/news'
import { assetLibraryApi } from '../api/assetLibrary'

export { getCachedProjectIcon, getCachedProjectName }

export const api = {
  listProjects: projectsApi.list,
  createProject: projectsApi.create,
  importProject: projectsApi.import,
  removeProject: projectsApi.remove,
  updateProject: projectsApi.update,
  reorderProjects: projectsApi.reorder,
  saveProjectTags: projectsApi.saveTags,
  duplicateProject: projectsApi.duplicate,
  openProject: projectsApi.open,
  stopProject: projectsApi.stop,
  listRunningProjects: () =>
    invoke<{ id: string; name: string; version: string; launched_at_ms: number }[]>(
      'list_running_projects',
    ),
  openProjectFolder: projectsApi.openFolder,
  openInEditor: projectsApi.openInEditor,
  getProjectSize: projectsApi.getSize,
  getProjectFileTree: projectsApi.getFileTree,
  pickFolder: projectsApi.pickFolder,
  pickFile: projectsApi.pickFile,
  pickSavePath: projectsApi.pickSavePath,
  pickDataFile: projectsApi.pickDataFile,
  getOsUsername: settingsApi.getOsUsername,
  notify: (title: string, body: string) =>
    invoke<void>('notify', { title, body }),
  exportWorkspaceBackup: settingsApi.exportWorkspaceBackup,
  importWorkspaceBackup: settingsApi.importWorkspaceBackup,
  exportAppBackup: settingsApi.exportAppBackup,
  importAppBackup: settingsApi.importAppBackup,
  gistSyncPush: settingsApi.gistSyncPush,
  gistSyncPull: settingsApi.gistSyncPull,
  gistSyncGetInfo: settingsApi.gistSyncGetInfo,
  gistSyncPullByUrl: settingsApi.gistSyncPullByUrl,
  gistSyncSaveGistUrl: settingsApi.gistSyncSaveGistUrl,
  gistSyncFetchBackup: settingsApi.gistSyncFetchBackup,
  getTimeInsights: settingsApi.getTimeInsights,
  exportProjectStats: projectsApi.exportProjectStats,
  importProjectStats: projectsApi.importProjectStats,
  clearTimeStats: projectsApi.clearTimeStats,
  getActivity: (range: 'daily' | 'weekly' | 'monthly' | 'yearly') =>
    invoke<[string, number][]>('get_activity', { range }),
  getProjectActivity: (projectId: string) =>
    invoke<[string, number][]>('get_project_activity', { projectId }),
  readImageFile: projectsApi.readImageFile,
  getProjectIcon: projectsApi.getIcon,
  getProjectName: projectsApi.getName,
  reintroduceDismissedProjects: projectsApi.reintroduceDismissed,
  clearProjectIconCache: projectsApi.clearIconCache,
  clearProjectNameCache: projectsApi.clearNameCache,

  fetchAvailableGodotVersions: (source?: string) =>
    versionsApi.fetchAvailable(source),
  downloadGodotVersion: versionsApi.download,
  pauseDownload: versionsApi.pauseDownload,
  resumeDownload: versionsApi.resumeDownload,
  reorderDownloadQueue: versionsApi.reorderDownloadQueue,
  cancelDownload: versionsApi.cancelDownload,
  listInstalledGodotVersions: versionsApi.listInstalled,
  renameGodotVersion: versionsApi.rename,
  deleteGodotVersion: versionsApi.delete,
  openGodotVersion: versionsApi.open,
  testGithubToken: versionsApi.testGithubToken,
  getGithubRateLimit: versionsApi.getGithubRateLimit,
  scanForVersions: versionsApi.scan,
  importVersion: versionsApi.import,
  importVersionZip: versionsApi.importZip,
  validateGodotFolder: versionsApi.validateFolder,

  cloneRepo: gitApi.clone,
  getGitStatus: gitApi.status,
  batchGitStatus: gitApi.batchStatus,
  openTerminal: gitApi.openTerminal,
  gitPull: gitApi.pull,
  gitFetch: gitApi.fetch,
  gitPush: gitApi.push,
  gitPushForce: gitApi.pushForce,
  gitLog: gitApi.log,
  gitLogEntries: gitApi.logEntries,
  gitListRemotes: gitApi.listRemotes,
  gitAheadBehind: gitApi.aheadBehind,
  gitShowCommit: gitApi.showCommit,
  gitStartFsWatcher: gitApi.startFsWatcher,
  gitStopFsWatcher: gitApi.stopFsWatcher,
  gitRemoteUrl: gitApi.remoteUrl,
  gitListBranches: gitApi.listBranches,
  gitSwitchBranch: gitApi.switchBranch,
  gitBranchPublish: gitApi.branchPublish,
  gitCreateBranch: gitApi.createBranch,
  gitDeleteBranch: gitApi.deleteBranch,
  gitStashPush: gitApi.stashPush,
  gitStashList: gitApi.stashList,
  gitStashApply: gitApi.stashApply,
  gitStashShow: gitApi.stashShow,
  gitStashPop: gitApi.stashPop,
  gitStashDrop: gitApi.stashDrop,
  gitChangedFiles: gitApi.changedFiles,
  gitDiscardChanges: gitApi.discardChanges,
  gitDiscardFile: gitApi.discardFile,
  gitInit: gitApi.init,
  gitInitProject: gitApi.initProject,
  gitIsAvailable: gitApi.isAvailable,
  gitStageFile: gitApi.stageFile,
  gitUnstageFile: gitApi.unstageFile,
  gitCommit: gitApi.commit,
  gitSetRemote: gitApi.setRemote,
  gitRemoveRemote: gitApi.removeRemote,
  gitFileDiff: gitApi.fileDiff,
  gitUndoCommit: gitApi.undoCommit,
  gitUndoPull: gitApi.undoPull,
  gitMergeConflictFiles: gitApi.mergeConflictFiles,
  gitResolveConflictOurs: gitApi.resolveConflictOurs,
  gitResolveConflictTheirs: gitApi.resolveConflictTheirs,
  gitResolveConflictManual: gitApi.resolveConflictManual,
  gitAbortMerge: gitApi.abortMerge,
  gitIsMerging: gitApi.isMerging,
  gitWorktreeList: gitApi.worktreeList,
  gitWorktreeSwitch: gitApi.worktreeSwitch,
  gitWorktreeAdd: gitApi.worktreeAdd,
  gitWorktreeRemove: gitApi.worktreeRemove,

  gitAuthGetState: gitAuthApi.getState,
  gitAuthCreateRemoteRepo: gitAuthApi.createRemoteRepo,
  gitAuthStartDeviceFlow: gitAuthApi.startDeviceFlow,
  gitAuthPollDeviceFlow: gitAuthApi.pollDeviceFlow,
  gitAuthDisconnect: gitAuthApi.disconnect,
  gitAuthSavePat: gitAuthApi.savePat,
  gitAuthRemovePat: gitAuthApi.removePat,
  gitAuthListUserRepos: gitAuthApi.listUserRepos,

  getSettings: settingsApi.get,
  updateSettings: settingsApi.update,
  resetSettings: settingsApi.reset,
  exportSettings: settingsApi.exportSettings,
  importSettings: settingsApi.importSettings,
  resetAppData: settingsApi.resetData,
  scanForProjects: settingsApi.scanForProjects,
  scanForProjectsWithInfo: settingsApi.scanForProjectsWithInfo,
  refreshTrayMenu: settingsApi.refreshTrayMenu,
  restartWatchers: settingsApi.restartWatchers,

  listTemplates: templatesApi.list,
  saveProjectAsTemplate: templatesApi.saveAsTemplate,
  deleteTemplate: templatesApi.delete,
  getTemplatePreview: templatesApi.getPreview,
  syncTemplatesWithScanDir: templatesApi.syncWithScanDir,

  listCategories: categoriesApi.list,
  createCategory: categoriesApi.create,
  renameCategory: categoriesApi.rename,
  updateCategory: categoriesApi.update,
  deleteCategory: categoriesApi.delete,
  reorderCategories: categoriesApi.reorder,

  listWorkspaces: workspacesApi.list,
  listWorkspaceScanDirs: workspacesApi.scanDirs,
  createWorkspace: workspacesApi.create,
  switchWorkspace: workspacesApi.switch,
  updateWorkspace: workspacesApi.update,
  deleteWorkspace: workspacesApi.delete,

  listChangelogEntries: changelogApi.list,
  addChangelogEntry: changelogApi.add,
  updateChangelogEntry: changelogApi.update,
  deleteChangelogEntry: changelogApi.delete,
  listGitTags: changelogApi.listGitTags,
  generateChangelogDraft: changelogApi.generateDraft,

  fetchUpdates: updatesApi.fetch,
  isPortableInstall: updatesApi.isPortableInstall,

  fetchGodotNews: newsApi.fetch,

  searchAssetLibrary: assetLibraryApi.search,
  installAssetAsTemplate: assetLibraryApi.installAsTemplate,
  installAsset: assetLibraryApi.install,
  downloadAsset: assetLibraryApi.download,
  searchAssetStore: assetLibraryApi.searchStore,
  downloadStoreAsset: assetLibraryApi.downloadStoreAsset,
  installStoreAsset: assetLibraryApi.installStoreAsset,
  listAssetLibraryCategories: assetLibraryApi.listCategories,
}
